Friend/urls.py
from django.urls import path
from . import views

app_name='Friend'

urlpatterns = [
	path('', views.homepage, name='homepage'),
    path('signup/', views.signupview, name='signupview'),
    path('login/', views.loginview, name='login'),
    path('logout/', views.logoutview, name='logoutview'),
    path('send_friend_request/<int:userID>/',
     views.send_friend_request, name = 'send friend request'),
    path('accept_friend_request/<int:requestID>/',
    	views.accept_friend_request, name='accept friend request'),
    path('to_accept_friend_request/', views.to_accept_request, name='to accept friend request'),
    path('ajax/requests/', views.postRequest, name="post_request"),
    path('friend_request_details/', views.friend_request_view, name='friend_request_detail'),
    path('api/friend_requests/', views.friend_request_list, name='friend_request_lsit'),
    # path('accepted_friend_request/<int:friendID>/', views.friend_request_accepted, name='accepted_friend_request'),
    path('accepted_friend_request/<int:friendID>/', views.friend_request_accepted, name='accepted_friend_request'),
    path('deleted_friend_request/<int:friendID>/', views.friend_request_deleted, name='deleted_friend_request'),
]

FriendRequest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('friend/',include('Friend.urls')),
    path('content/',include('content.urls')),
    
]

blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    ThreadCreateView,
    UserPostListView,
)
from . import views

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='blog_home'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    #path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/details/<int:pk>/',views.details, name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('thread/new/', ThreadCreateView.as_view(), name='thread-create'),
    path('about/', views.about, name='blog_about'),
]

Friend/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
	friends = models.ManyToManyField("User", blank=True)


class Friend_Request(models.Model):
	from_user = models.ForeignKey(
		User, related_name='from_user', on_delete = models.CASCADE)
	to_user = models.ForeignKey(
		User, related_name='to_user', on_delete=models.CASCADE)
	






		

Friend/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm

from .models import User, Friend_Request
from django import forms

class UserCreateForm(UserCreationForm):

	class Meta(UserCreationForm):
		model = User
		fields = ('username', 'password1', 'password2')

class FriendRequestCreateForm(forms.ModelForm):

	class Meta:
		model = Friend_Request
		fields = ("__all__")

Friend/views.py
from django.http import HttpResponse, JsonResponse
from django.core import serializers
# from django.contrib.auth.models import User
from .models import User, Friend_Request
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import UserCreateForm, FriendRequestCreateForm
from .serializers import FriendRequestSerializer
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from django.shortcuts import get_object_or_404

def signupview(request):
	if request.method == "POST":
		form = UserCreateForm(request.POST)
		if form.is_valid():
			new_user = form.save()
			new_user = authenticate(
				username = form.cleaned_data['username'],
				password = form.cleaned_data['password1'])
			login(request, new_user)
			return HttpResponse('loggedIn')
		else:
			print(request.POST, form.errors)
			return render(request, 'signup.html', {'form': form, 'error': form.errors})
	else:
		form = UserCreateForm()
		return render(request, 'signup.html', {'form': form})

def loginview(request):
	if request.method == "POST":
		user = authenticate(
			request,
			username = request.POST['username'],
			password = request.POST['password'])
		print(request.POST['username'])
		print(request.POST['password'])

		print(user)
		
		if user is not None:
			login(request, user)
			return HttpResponse('login Successful')
			
		else:			
			return HttpResponse('login Unsuccessful')
	else:
		
		return render(request, 'login.html')

def logoutview(request):
	
	logout(request)
	return HttpResponse('logout successful')


def homepage(request):
	return render(request, 'homepage.html')


@login_required
def send_friend_request(request, userID):
	from_user = request.user
	to_user = User.objects.get(id =userID)
	friend_request, created = Friend_Request.objects.get_or_create(
		from_user=from_user, to_user=to_user)
	if created:
		return HttpResponse('friend request sent')
	else:
		return HttpResponse('friend request was already sent')


@login_required
def to_accept_request(request):
	if request.method == 'GET':
		to_user = request.user
		friend_requests =  Friend_Request.objects.filter(to_user = to_user)
		return render(request, 'accept_friend_request.html', {'all_friend_requests': friend_requests})
	else:
		return HttpResponse("Request method is not GET")

@login_required
def accept_friend_request(request, requestID):
	friend_request = Friend_Request.objects.get(id=requestID)
	if friend_request.to_user == request.user:		
		friend_request.to_user.friends.add(friend_request.from_user)
		friend_request.from_user.friends.add(friend_request.to_user)
		friend_request.delete()
		msg = 'Friend Request Accepted'		
	else:		
		msg = 'Friend Request Not Accepted'
	return render(request, 'accepted_friend_request.html', {'msg': msg, 'friend_request': friend_request})

def displayRequests(request):
	form = FriendRequestCreateForm()
	friend_requests = Friend_Request.objects.all()
	return render(request, "index.html", {"form": form, "friend_requests": friend_requests})

def postRequest(request):
	if request.is_ajax and request.method == "POST":
		form = FriendRequestCreateForm(request.POST)
		print(form)
		if form.is_valid():
			instance= form.save()
			ser_instance = serializers.serialize('json', [instance, ])
			return JsonResponse({'instance':ser_instance}, status=200)
		else:
			return JsonResponse({"error": form.errors}, status = 400)
	return JsonResponse({'error':""}, status=400)

@csrf_exempt
def friend_request_list(request):
    """
    List all required messages, or create a new message.
    """
    if request.method == 'GET':
    	userID= request.user.id
    	friend_requests = Friend_Request.objects.filter(to_user_id=userID)
    	ids = [friend_request.id for friend_request in friend_requests]
    	from_users = [friend_request.from_user for friend_request in friend_requests]
    	serializer = FriendRequestSerializer(friend_requests, many=True, context={'request': request})
    	for friend_request in friend_requests:
    		friend_request.save()    	  	
    	
    	return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = FriendRequestSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)



def friend_request_view(request):
	if not request.user.is_authenticated:
		return HttpResponse('Not allowed')

	if request.method == "GET":
		to_user = request.user
		friend_requests = Friend_Request.objects.filter(to_user=to_user)
		
		return render(request, 'new_accept_friend_request.html', {'all_friend_requests': friend_requests})
	else:
		return HttpResponse("Request method is not GET")

def friend_request_accepted(request, friendID):
	
	accepted_friend = get_object_or_404(User, pk=friendID)
	friend_request = get_object_or_404(Friend_Request, from_user_id=friendID)
	friend_request.delete()
	msg = str(request.user) + ' is now friends with ' + str(accepted_friend.username)
	# return render(request, 'accepted_friend_request.html', {'friend': accepted_friend})
	return render(request, 'new_accept_friend_request.html', {'msg': msg})

def friend_request_deleted(request, friendID):	
	accepted_friend = get_object_or_404(User, pk=friendID)
	friend_request = get_object_or_404(Friend_Request, from_user_id=friendID)
	friend_request.delete()
	msg = 'Request from  ' + str(accepted_friend.username)	+ ' was deleted'
	return render(request, 'new_accept_friend_request.html', {'msg': msg})

# def unfriend(request, friendID):	
# 	from_user = get_object_or_404(User, pk=friendID)
# 	friend_request = get_object_or_404(Friend_Request, to_user_id = request.user.id, from_user_id = friendID)
# 	if not friend_request:
# 		friend_request = get_object_or_404(Friend_Request, from_user_id = request.user.id, to_user_id = friendID)
# 	friend_request.delete()
# 	msg = ' You have successfully unfriended '+ str(from_user.username)

# def is_mutual_friend(request, otherID):
# 	other_user = get_object_or_404(User, pk=otherID)
	

		

Friend/templates/accept_friend_request.html
{% for friend_request in all_friend_requests %}
<h1>{{friend_request.from_user}}
	
	<a class="accept-button" id="accept{{friend_request.id}}" data-catid="{{ friend_request.id }}"
	href={% url 'Friend:accept friend request' requestID=friend_request.id %}>accept friend request</a>
</h1>
<h1>Done</h1>
{% endfor %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script type="text/javascript">
    $('.acceptbutton').click(function(){
    var catid;
    catid = $(this).attr("data-catid");

    $.ajax(
    {
        type:"GET",
        url: "/to_accept_friend_request",
        data:{
                 friend_request_id: catid
        },
        success: function( data ) 

        {	
        	
            $( '#accept'+ catid ).remove();
            
        }
        })
});
</script>

Friend/templates/accepted_friend_request.html
<h1>{{request.user}} is now friends with {{friend.username}}</h1>

Friend/templates/base.html
{% load staticfiles %}
  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <!--Import jQuery before materialize.js-->
         <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
    </head>

    <body>
    {% block body %}
        <div class="section blue lighten-3">
            <div class="container white-text center-align text">
            <h2>A special Chat for Khidmah IT.</h2>
            <p>A Chatting App.</p>
            </div>
        </div>
        <div class="container">
            <div class="row">
            <div class="col s12 m8 l6 offset-m2 offset-l3">
                <div class="section center-block">
                <div>
                    {% block form %}
                    <h3>
                    Login
                    </h3>
                    <form id="login-form" class="form-group" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="username" id="id_username" type="text">
                                <label for="id_username">Username</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="password" id="id_password" type="password">
                                <label for="id_password">Password</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s8">
                                <a href="{% url 'register' %}">Register</a>
                            </div>
                            <div class="col s4">
                            <div class="right">
                                <button class="btn blue waves-effect waves-light pull-s12">Login</button>
                            </div>
                            </div>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
            </div>
            </div>
        </div>
        {% endblock %}
    </body>

  </html>

Friend/templates/homepage.html
{% if user.is_authenticated %}
<h2> Logged in as </h2>
<h1> {{user}}</h1>
{% else %}
<a href="/friend/login/">Please Login</a>
<!-- <a href="/friend/login/">Please Logout</a> -->
{% endif %}

Friend/templates/index.html
{% extends "main.html" %}

{% block content %}
<div class="container">
    <form id="requests-form">
		{% csrf_token %}
		{% for field in form %}
		<div class="form-group row">
			<label class="col-sm-2 col-form-label">
			<strong>{{ field.label }}</strong>
			</label>
			<div class="col-sm-10">
			{{ field }}
			</div>
		</div>
		{% endfor %}
		<div class="form-group row">
		<input type="submit" class="btn btn-primary" value="Create Participant" />
		</div>
    <form>
</div>

<div class="container">
    <table class="table table-bordered" id="showdata">
        <thead>
            <tr>
                <th scope="col">From </th>
                <th scope="col">To</th>
                
            </tr>
        </thead>
        <tbody>
        {% for friend_request in friend_requests %}
        <tr>
            <td>{{friend_request.from_user}}</td>
            <td>{{friend_request.to_user}}</td>
            
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

{% block javascript %}
<script>
    $("#requests-form").submit(function (e) {
        // preventing default actions
        e.preventDefault();
        // serialize the data for sending the form data.
        var serializedData = $(this).serialize();
        // Ajax Call
        $.ajax({
            type: 'POST',
            url: "{% url 'post_request' %}",
            data: serializedData,
			// handle a successful response
            success: function (response) {
                // On successful, clear all form data
                $("#requests-form").trigger('reset');

                // Display new participant to table
                var instance = JSON.parse(response["instance"]);
                var fields = instance[0]["fields"];
                $("#showdata tbody").prepend(
                   `<tr>
                    <td>${fields["from_user"]||""}</td>
                    <td>${fields["to_user"]||""}</td>                    
                    </tr>`
                )
            },
            error: function (response) {
                // alert non successful response
                alert(response["responseJSON"]["error"]);
            }
        })
    })
</script>
{% endblock javascript %}

Friend/templates/login.html
<form class="login-form" action = {% url 'Friend:login' %} method="post">
	{% csrf_token %}
	<div>
		<label for="username">Username : </label>
		<input type="text" name="username" />
	</div>
	<div>
		<label for="password">Password :</label>
		<input type="password" name="password" />
	</div>
	<div>
		<button type="submit">Login</button>

	</div>
</form>

Friend/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>

<body>
    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

Friend/templates/new_accept_friend_request.html
<!-- 

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

    {% for message in messages %}
    {% if message.sender == request.user %}
<div class="card-panel right" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">You</div>
    {{ message }}
</div>
    {% else %}
<div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.sender }}</div>
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,1000)
})
</script> -->


<!-- {% for friend_request in all_friend_requests %}
<h2>{{friend_request.from_user}}
    
    <a class="accept-button" id="accept{{friend_request.id}}" data-catid="{{ friend_request.id }}"
    href={% url 'Friend:accept friend request' requestID=friend_request.id %}>accept friend request</a>
</h2>
<h1>Done</h1>
{% endfor %}
 -->
 {% if msg %}
    {{ msg }}
{% endif %}
 <div id="new">
        No new friends request 

 </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script type="text/javascript">
   
   $(function () {
   
    console.log('HERE1')
    setInterval(function receive() {
        console.log('HERE2')
    var url = '/friend/api/friend_requests/'
    $.get(url, function (data) {
        console.log(data);
        if (data.length !== 0)
        {
            document.getElementById('new').innerHTML = "";
            for(var i=0;i<data.length;i++) {
                // console.log(data[i].from_user);
                // console.log(data[i].ids[i])
                var element = document.getElementById('new')
                var header = document.createElement("h2")
                var text = document.createTextNode(data[i].from_user)
                header.appendChild(text)
                element.appendChild(header)

                var acceptlink = document.createElement("a")
                var accepttext = document.createTextNode("Accept")
                acceptlink.appendChild(accepttext)
                acceptlink.href = '/friend/accepted_friend_request/' + data[i].from_user_id + '/'
                // acceptlink.href = '/friend/accepted_friend_request/'
                

                var deletelink = document.createElement("a")
                var deletetext = document.createTextNode("Delete")
                deletelink.appendChild(deletetext)
                deletelink.href = '/friend/deleted_friend_request/' + data[i].from_user_id + '/'

                header.appendChild(acceptlink)
                header.appendChild(deletelink)

                // if element == null{
                //     element.innerHTML = "No friend requests"
                // }


                
            }            
        }
    })
},1000)
})
</script>

Friend/templates/send_friend_request.html
<ul class = "all_users">
	{% for user in allusers %}
	{% if not user.is_superuser %}
	{% if user not in request.user.friends.all and user != request.user %}


	<!-- <h1>{{user}}<a href="/friend/send_friend_request/{{user.id}}/">Send Friend Request</a></h1> -->
	<h1>{{user}}<a href={% url 'Friend:send_friend_request' userID=user.id %}>Send Friend Request</a></h1>
	{% endif %}
	{% endif %}
	{% endfor %}
	<a href="/friend/logout/">Logout</a>
</ul>

Friend/templates/signup.html
<form class="signup-form" method="POST" action="/friend/signup/">
	{% csrf_token %}
	{% for field in form %}
	<p class = 'error'>{{field.errors}}</p>
	<div class="field-wrapper">
		<div>{{field.label_tag}}</div>
		<div>
			{{field}}
			<p>{{field.help_text}}</p>
		</div>
	</div>
	{% endfor %}
	<div class="field-wrapper">
		<button type="submit">Signup</button>button>
	</div>

</form>